# Generated by Django 4.1.2 on 2022-11-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Teacher',
            new_name='StudentTeacher',
        ),
    ]
