# Generated by Django 4.1.2 on 2022-11-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_rename_student_teacher_studentteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_type',
            field=models.IntegerField(),
        ),
    ]
