# Generated by Django 4.1.2 on 2022-11-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_profiletypes_alter_users_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
