# Generated by Django 4.1.2 on 2022-11-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'A user with such username already exists, please, try another one'}, max_length=255, unique=True),
        ),
    ]
