# Generated by Django 4.1.2 on 2022-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'This email has already been registered'}, max_length=254, unique=True),
        ),
    ]
