# Generated by Django 4.1.2 on 2022-11-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='subject',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'A user with such username already exists, please, try another one'}, max_length=255, unique=True),
        ),
    ]
