# Generated by Django 4.1.2 on 2022-11-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0011_subjects_alter_users_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
